### PR TITLE
Move Scss file to a separate scss folder

### PR DESCRIPTION
**Pull request by joshmedeski**
Hi Peter, this is a simple pull request that would cause a breaking change but would be better for the Sass community that uses this package.

I'm using your plugin by importing the Scss file into my main stylesheet. According to my team's syntax standards, we do not include the `.scss` extenstion when importing a file.

This means when I use the following code...

```
@import 'bower_components/foundation-datepicker/css/foundation-datepicker';
```

...I get the following error...

```
Error: File to import not found or unreadable
```

Sass is looking for a file called `foundation-datepicker.scss` and it's finding multiple results (`foundation-datepicker.scss` and `foundation-datepicker.css`)

---

This PR moves `foundation-datepicker.scss` into a separate directory `/scss/foundationdatepicker.scss`.

This will fix the Sass error and make it easier for Sass users to find the `scss` file (it felt weird in the `css` folder).

I hope you like the update. My team is currently disabling our linter to explicitly add the `.scss` extension to the sass file, but we hope to see this project updated so our code is clean again.

Thanks for the awesome plugin!

### CODE REVIEW

**Comment by najlepsiwebdesigner** [comment]
Thanks for explanation, merged! ;)

**Comment by joshmedeski** [comment]
Thanks @najlepsiwebdesigner!

Please be aware of semantic versioning. Since we changed the folder structure, it is considered a breaking change. It would have been more appropriate to bump it up to v.1.6.0 😄 

My team is doing a hot fix but I'm not sure how many other people using your tool are going to see errors in their build tools because they locked bower to v1.5.

Just something to think about moving forward, but thanks again for approving this code!

**Comment by najlepsiwebdesigner** [comment]
Hi Josh,

version 1.5.5 was planned already with bug fixes, I've just included your pull request because it looked urgent. I will not bump to 1.6.0 until I will implement all the stuff I want for that version (look at "will be implemented" tags in issues).

However, if we consider this file structure change as breaking change, according to the semantic versioning, I would have to bump major version number, not minor or patch number. ;)

**Comment by joshmedeski** [comment]
Glad you have everything planned out 😄 

I guess changing a source file's location in the project will not "break" the project, you would just have to update the path in your code. Not sure if that's major or minor, but it feels scary when that kind of change is only put in a patch 😉

**Pull request merged**
