### PR TITLE
Remove incorrect validations

### LINKED ISSUE #176: M and MM formats don't work with Foundation Abide
Using either the "M" or "MM" formats for a datepicker in a form that uses Foundation Abide validation causes the date input to be incorrectly flagged as invalid.

For instance, setting `format: 'MM yyyy'` results in dates such as "September 2016", but datepicker attempts to validate the date value by simply comparing it's length to the length of the format string (starting at line 415):

``` javascript
            if (date.length > this.formatText.length) {
                    $(this.picker).addClass('is-invalid')
                    $(this.element).addClass('is-invalid-input')
                    return;
            }
```

In this example case, the length of "September 2016" is > than the length of "MM yyyy", so the value is incorrectly flagged as invalid.

A better approach might be to define a validation regex for each format.

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Hi!

As mentioned in #176 & #209, the validation done by foundation-datepicker is incorrect since there's no guarantee that the length of the format string will match the actual length of a date. Moreover, this validation has been biting us in combination with the https://github.com/sgruhier/foundation_rails_helper gem. If a submitted form has errors in the date field, this gem will generate form input with "foundation friendly errors". However, this piece of JS will actually remove part of them making them look weird.

Also, in my opinion, users wanting to perform client side validations should use foundation-abide which is more powerful anyways.

So because of all of the above reasons, I think we should remove these incorrect validations from the library.

Fixes #176 & #209.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
I committed to package-lock.json file since it helps a bit with ensuring all contributors get the same environment, and it prevents source control untracked files from being generated while development. Let me know it you want that removed.

**Comment by deivid-rodriguez** [comment]
I moved the `package-lock.json` addition to a separate PR to make reviewing this easier.

**Comment by deivid-rodriguez** [comment]
@najlepsiwebdesigner Any news here? We'd prefer to not fork the library and have some valuable feedback from you :)

**Comment by najlepsiwebdesigner** [comment]
Hi! I'm sorry for late answer, I am currently finishing my PhD so I'm "little bit" busy. I plan to review all the changes proposed in PRs and issues during August. Thank you for understanding ;)

**Comment by deivid-rodriguez** [comment]
He @najlepsiwebdesigner, just a ping since it's september now. I hope you finished your PhD successfully and you're doing great! :)

**Comment by deivid-rodriguez** [comment]
Any news?

**Comment by deivid-rodriguez** [comment]
Thanks so much @najlepsiwebdesigner!

**Pull request merged**
